#ifndef _LGE_ATS_FLEX_H_
#define _LGE_ATS_FLEX_H_

#define ONCRPC_LGE_GET_FLEX_MCC_PROC 7 
#define ONCRPC_LGE_GET_FLEX_MNC_PROC 8 
#define ONCRPC_LGE_GET_FLEX_OPERATOR_CODE_PROC 9 
#define ONCRPC_LGE_GET_FLEX_COUNTRY_CODE_PROC 10 


#endif 
