
#ifndef _MACH_QDSP5_V2_AUDIO_DEF_H
#define _MACH_QDSP5_V2_AUDIO_DEF_H


#define SNDDEV_CAP_RX 0x1 
#define SNDDEV_CAP_TX 0x2 
#define SNDDEV_CAP_VOICE 0x4 
#define SNDDEV_CAP_PLAYBACK 0x8 
#define SNDDEV_CAP_FM 0x10 
#define SNDDEV_CAP_TTY 0x20 
#define VOC_NB_INDEX	0
#define VOC_WB_INDEX	1
#define VOC_RX_VOL_ARRAY_NUM	2


#define SNDDEV_DEV_VOL_DIGITAL  0x1  
#define SNDDEV_DEV_VOL_ANALOG   0x2  

#endif 
