



#ifndef __ASM_ARCH_MXC_BOARD_MX31PDK_H__
#define __ASM_ARCH_MXC_BOARD_MX31PDK_H__




#define DEBUG_BASE_ADDRESS		CS5_IO_ADDRESS(CS5_BASE_ADDR)


#define LAN9217_BASE_ADDR		CS5_BASE_ADDR


#define CPLD_ADDR			(DEBUG_BASE_ADDRESS + 0x20000)


#define CPLD_LED_REG			(CPLD_ADDR + 0x00)

#define CPLD_SWITCH_BUTTONS_REG	(EXPIO_ADDR + 0x08)

#define CPLD_INT_STATUS_REG		(CPLD_ADDR + 0x10)
#define CPLD_INT_MASK_REG		(CPLD_ADDR + 0x38)
#define CPLD_INT_RESET_REG		(CPLD_ADDR + 0x20)

#define CPLD_MAGIC_NUMBER1_REG		(CPLD_ADDR + 0x40)
#define CPLD_MAGIC_NUMBER2_REG		(CPLD_ADDR + 0x48)

#define CPLD_CODE_VER_REG		(CPLD_ADDR + 0x50)

#define CPLD_MAGIC_NUMBER3_REG		(CPLD_ADDR + 0x58)

#define CPLD_MODULE_RESET_REG		(CPLD_ADDR + 0x60)

#define CPLD_MCU_BOARD_ID_REG		(CPLD_ADDR + 0x68)


#define EXPIO_PARENT_INT	IOMUX_TO_IRQ(MX31_PIN_GPIO1_1)

#define MXC_EXP_IO_BASE		(MXC_BOARD_IRQ_START)
#define MXC_IRQ_TO_EXPIO(irq)	((irq) - MXC_EXP_IO_BASE)

#define EXPIO_INT_ENET		(MXC_EXP_IO_BASE + 0)
#define EXPIO_INT_XUART_A	(MXC_EXP_IO_BASE + 1)
#define EXPIO_INT_XUART_B	(MXC_EXP_IO_BASE + 2)
#define EXPIO_INT_BUTTON_A	(MXC_EXP_IO_BASE + 3)
#define EXPIO_INT_BUTTON_B	(MXC_EXP_IO_BASE + 4)

#define MXC_MAX_EXP_IO_LINES	16

#endif 
